class Config:
    MYSQL_HOST = 'localhost'
    MYSQL_USER = 'root'
    MYSQL_PASSWORD = ''
    MYSQL_DB = 'dormease_db'
    GMAIL_USER     = 'jodimayo98@gmail.com'
    GMAIL_PASSWORD = 'ykdd bjpt gshq vvge'
    MAIL_FROM      = 'DormEase <jodimayo98@gmail.com>'
    SMS_API_KEY    = 'sk-2b10mqv6o6xtt5d6hidrebnspsravu9p'
    SMS_API_URL    = 'https://smsapiph.onrender.com/api/v1/send/sms'
    SMS_SENDER_ID  = 'DormEase'